services:
  php:
    image: php:apache
    volumes:
      - ~/docker/apache/html:/var/www/html
      - ~/docker/apache/common.conf:/etc/apache2/conf-enabled/common.conf
      - ~/docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ~/docker/apache/ssl:/root/ssl
      - ~/docker/apache/static:/root/static
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:latest
    volumes:
      - ~/docker/mysql/conf.d:/etc/mysql/conf.d
      - ~/docker/mysql/mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - 3306:3306
