services:
  nginx:
    image: nginx:latest
    volumes:
      - ./global.conf:/etc/nginx/conf.d/global.conf
      - ~/docker/nginx/common.conf:/etc/nginx/conf.d/common.conf
      - ~/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ~/docker/nginx/ssl:/root/ssl
      - ~/docker/nginx/static:/root/static
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
