services:
  primary:
    image: mariadb:latest
    volumes:
      - ~/docker/mariadb/conf.d:/etc/mysql/conf.d
      - ~/docker/mariadb/mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 3306:3306
  secondary:
    image: mariadb:latest
    volumes:
      - ~/docker/mariadb/secondary/conf.d:/etc/mysql/conf.d
      - ~/docker/mariadb/secondary/mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - 3307:3306
