services:
  primary:
    image: mariadb:latest
    volumes:
      - ~/docker/mariadb/conf.d:/etc/mysql/conf.d
      - ~/docker/mariadb/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  secondary:
    image: mariadb:latest
    volumes:
      - ~/docker/mariadb/secondary/conf.d:/etc/mysql/conf.d
      - ~/docker/mariadb/secondary/mysql:/var/lib/mysql
    ports:
      - 3307:3306
