services:
  primary:
    image: postgres:latest
    volumes:
      - ~/docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  secondary:
    image: postgres:latest
    volumes:
      - ~/docker/postgres/secondary/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
